### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by anaraquelmendes** [anaraquelmendes/animal-rescue-website#3]
This was the most difficult term of our course. I believe that I met the expectations within what I could accomplish. As for the website, I think it could be much better if I had more time to dedicate to it. I think I deserve an A-.

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
